name: Test2
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  something:
    name: Something
    runs-on: ubuntu-16.04
    timeout-minutes: 30
    steps:
      - name: Somethinggg1
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }} 
        run: echo "$GITHUB_CONTEXT"
